// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7M3KYWSbANahQ_w2pP68RMy7gk_xAK8',
    appId: '1:858763117515:web:1d1f91569a5494b91eec4e',
    messagingSenderId: '858763117515',
    projectId: 'algorithm-control',
    authDomain: 'algorithm-control.firebaseapp.com',
    storageBucket: 'algorithm-control.firebasestorage.app',
    measurementId: 'G-LB78NPM7QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsAIMj6zpiikdBhPfM0laYU8rLoGvI-0',
    appId: '1:858763117515:android:f39e52e13e1576991eec4e',
    messagingSenderId: '858763117515',
    projectId: 'algorithm-control',
    storageBucket: 'algorithm-control.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IXaMx7SFzmQWOZI79Tl6EsomyrPct1s',
    appId: '1:858763117515:ios:8297ffc453cb2c661eec4e',
    messagingSenderId: '858763117515',
    projectId: 'algorithm-control',
    storageBucket: 'algorithm-control.firebasestorage.app',
    iosBundleId: 'com.example.algorithmControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IXaMx7SFzmQWOZI79Tl6EsomyrPct1s',
    appId: '1:858763117515:ios:8297ffc453cb2c661eec4e',
    messagingSenderId: '858763117515',
    projectId: 'algorithm-control',
    storageBucket: 'algorithm-control.firebasestorage.app',
    iosBundleId: 'com.example.algorithmControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV7M3KYWSbANahQ_w2pP68RMy7gk_xAK8',
    appId: '1:858763117515:web:1d1f91569a5494b91eec4e',
    messagingSenderId: '858763117515',
    projectId: 'algorithm-control',
    authDomain: 'algorithm-control.firebaseapp.com',
    storageBucket: 'algorithm-control.firebasestorage.app',
    measurementId: 'G-LB78NPM7QE',
  );

}